=== abramvandergeest/catalystml/versions/0.1.6/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "The Root Schema",
    "description": "Defines CML JSON to transform data.",
    "properties": {
        "model":{
            "$id": "#/properties/model",
            "type": "object",
            "title": "The Model Schema",
            "description": "A description of model CML JSON will feed to or use of JSON.",
            "default": {},
            "examples": []
        },
        "name": {
            "$id": "#/properties/name",
            "type": "string",
            "title": "The Name Schema",
            "description": "Name for catalyst-ml JSON object.",
            "default": "Name",
            "examples": [
                "FinancialStructure"
            ]
        },
        "description": {
            "$id": "#/properties/description",
            "type": "string",
            "title": "The Description Schema",
            "description": "A place to give a description of overall use/purpose of CML JSON object.",
            "default": "",
            "examples": [
                "Cleaning some financial data"
            ]
        },
        "version": {
            "$id": "#/properties/version",
            "type": "string",
            "title": "The Version Schema",
            "description": "To help track versions of CML Object.",
            "default": "0.0.0",
            "examples": [
                "0.0.1",
                "1.0.1"
            ]
        },
        "createdDate": {
            "$id": "#/properties/createdDate",
            "type": "string",
            "title": "The Createddate Schema",
            "description": "Gives date of when creation or update of CML object.",
            "default": "",
            "examples": [
                "YYYYMMDD",
                "20200101"
            ]
        },
        "input": {
            "$id": "#/properties/input",
            "type": "array",
            "title": "The Input Schema",
            "description": "Describes types properties of input data.",
            "default": [],
            "items": {
                "$id": "#/properties/input/items",
                "type": "object",
                "title": "The Items Schema",
                "description": "Defines a aingle input's meta data.",
                "default": {},
                "examples": [
                    {
                        "label": "inputs",
                        "type": "array"
                    }
                ],
                "required": [
                    "type",
                    "label"
                ],
                "properties": {
                    "type": {
                        "$id": "#/properties/input/items/properties/type",
                        "type": "string",
                        "title": "The Type Schema",
                        "description": "Tells what type the input will be.",
                        "default": "",
                        "examples": [
                            "array",
                            "map"
                        ]
                    },
                    "label": {
                        "$id": "#/properties/input/items/properties/label",
                        "type": "string",
                        "title": "The Label Schema",
                        "description": "Gives a variable name to reference this data in structures or output.",
                        "default": "",
                        "examples": [
                            "inputs",
                            "datain"
                        ]
                    }
                }
            }
        },
        "structure": {
            "$id": "#/properties/structure",
            "type": "array",
            "title": "The Structure Schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "items": {
                "$id": "#/properties/structure/items",
                "type": "object",
                "title": "The Items Schema",
                "description": "An explanation about the purpose of this instance.",
                "default": {},
                "examples": [
                    {
                        "output": "datatemp",
                        "input": {
                            "data": "$inputs"
                        },
                        "operation": "concatMap"
                    },
                    {
                        "output": "datatemp['Age']",
                        "input": {
                            "data": "$datatemp['Age']",
                            "value": 100.0,
                            "minval": 18.0
                        },
                        "operation": "normalize"
                    }
                ],
                "required": [
                    "operation",
                    "input",
                    "output"
                ],
                "properties": {
                    "operation": {
                        "$id": "#/properties/structure/items/properties/operation",
                        "type": "string",
                        "title": "The Operation Schema",
                        "description": "Gives Name of Operation to run.",
                        "default": "",
                        "examples": [
                            "concatMap"
                        ]
                    },
                    "input": {
                        "$id": "#/properties/structure/items/properties/input",
                        "type": "object",
                        "title": "The Input Schema",
                        "description": "An explanation about the purpose of this instance.",
                        "default": {},
                        "patternProperties": {
                            "^.*$": {
                              "anyOf": [
                                {"type": "string"},
                                {"type": "null"}
                              ]
                            }
                          },
                        "additionalProperties": false,
                        "examples": [
                            {
                                "data": "$inputs"
                            }
                        ]
                    },
                    "params": {
                        "$id": "#/properties/structure/items/properties/params",
                        "type": "object",
                        "title": "The Params Schema",
                        "description": "Defining Parameters for the operation.",
                        "default": {},
                        "patternProperties": {
                            "^.*$": {
                              "anyOf": [
                                {"type": "string"},
                                {"type": "null"}
                              ]
                            }
                          },
                        "additionalProperties": false,
                        "examples": [
                            {
                                "data": "$inputs"
                            }
                        ]
                    },
                    "output": {
                        "$id": "#/properties/structure/items/properties/output",
                        "type": "string",
                        "title": "The Output Schema",
                        "description": "The label given to the data object being output by the operation so it can be used as a variable in other operations.",
                        "default": "",
                        "examples": [
                            "datatemp"
                        ]
                    }
                }
            }
        },
        "output": {
            "$id": "#/properties/output",
            "type": "object",
            "title": "The Output Schema",
            "description": "Defines the output of the cml object.",
            "default": {},
            "examples": [
                {
                    "type": "map",
                    "data": "$datatab"
                }
            ],
            "required": [
                "type",
                "data"
            ],
            "properties": {
                "type": {
                    "$id": "#/properties/output/properties/type",
                    "type": "string",
                    "title": "The Type Schema",
                    "description": "Describes the root type of the output data.",
                    "default": "",
                    "examples": [
                        "map"
                    ]
                },
                "data": {
                    "$id": "#/properties/output/properties/data",
                    "type": "object",
                    "title": "The Data Schema",
                    "description": "Building of output from defined variables.",
                    "default": {},
                    "examples": [
                        "$datatab"
                    ]
                }
            }
        }
    }
}

=== abramvandergeest/catalystml/demos/boxdrop_structured/cml_sample.json
{
    "name":"BoxDrop",
    "description":"Converts a matrix of accelerometers to an input map with magnitudes included",
    "version":"0.1.1",
    "createdDate":"20190130",
    "model":{
        "framework":"Tensorflow",
        "tags":"serve",
        "signatureDefs":"def_signature"
    },
	"input": [
    {
		    "type": "array",
        "dimensions": 2,
        "shape":[3,3],
        "label":"input"
    }
	],
	"structure": [
    {
      "operation":"norm",
      "input":{"data":"$input"},
      "params":{"axis":1},
      "output":"mag"
    },
    {
      "operation":"addCol2Table",
      "input": 
      {
          "matrix":"$input",
          "col":"$mag"
      },
      "output":"accel"
    },
    {
      "operation":"flatten",
      "input":{
        "data":"$accel"
      },
      "output":"flat"
    },
    {
      "operation":"table2map",
      "input":{
        "table":"$flat",
        "colKeys":["0_0","1_0","2_0","amag_0","0_1","1_1","2_1","amag_1","0_2","1_2","2_2","amag_2"]
      },
      "output":"finalout"
    }
  ],
	"output": {
    "type": "map",
    "data":{"feat1":"$finalout"}
	}
}

=== abramvandergeest/catalystml/demos/healthcare_price_example/healtchcare_demo.json
{
  "name":"Healthcare",
  "description":"Transforms healthcare mostly catagorical data to useable format",
  "version":"0.0.1",
  "createdDate":"20190719",
  "model":{
      "framework":"Tensorflow",
      "tags":"serve",
      "signatureDefs":"def_signature"
  },
"input": [
  {
      "type": "unkown",
      "label":"dataIn"
  }
],
"structure": [
                {
                  "operation":"replaceValue",
                  "input":
                  {
                    "data":"$dataIn",
                    "replaceMap":{"Yes":1,"No":0}
                  },
                  "params":{"col":
                    [
                      "cancer",
                      "heartdisease",
                      "cholesterol",
                      "diabetes",
                      "highbloodpressure",
                      "smoker"
                      ]},
                  "output":"datatemp"
                },
                {
                  "operation":"replaceValue",
                  "input":
                  {
                    "data":"$datatemp",
                    "replaceMap":{"Working":1,"NotWorking":0}
                  },
                  "params":{"col":"currentlyworking"},
                  "output":"datatemp"
                },
                {
                  "operation":"normalize",
                  "input":{
                    "data":"$datatemp['age']",
                    "value":100,
                    "minvalue":18
                  },
                  "output":"datatemp['age']"
                },
                {
                  "operation":"normalize",
                  "input":{
                    "data":"$datatemp['bmi']",
                    "value":60,
                    "minvalue":15
                  },
                  "output":"datatemp['bmi']"
                },
                {
                  "operation":"oneHotEncoding",
                  "input":{"data":"$datatemp"},
                  "params":{
                    "inputColumns": ["maritalstatus", "state", "product", "occupation"],
                    "keepOrig":false
                  },
                  "output":"datatemp"
                },
                {
                  "operation":"dropCol",
                  "input" :{
                    "data": "$datatemp"
                  },
                  "params":{
                    "col": ["city","lattitude","longitude","zipcode","year"],
                    "separateOut":false
                  },
                  "output":"datatemp"
                }
           ],
"output": {
  "type": "map",
  "data":{
    "output":"$datatemp"
  }
}
}
